name: mini_tracker
description: "A clean architecture Flutter app for tracking habits and tasks."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  uuid: ^4.5.2
  equatable: ^2.0.8
  logger: ^2.6.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true